blank_issues_enabled: false
contact_links:
  - name: Documentation pages
    url: https://github.com/SalvaChiLlo/statistics-for-endurain/blob/master/docs/home.md
    about: Everything you need to setup and configure this app
