name: Help / question
description: Ask for help
labels: ["question / help"]
assignees:
  - SalvaChiLlo
body:
  - type: markdown
    attributes:
      value: |
        ## Before opening an issue

        * Be sure to check the [documentation](https://github.com/SalvaChiLlo/statistics-for-endurain/blob/master/docs/home.md). A lot of common issues are already addressed in the troubleshooting section.
        * Search the [existing GitHub issues](https://github.com/SalvaChiLlo/statistics-for-endurain/issues?q=is:issue) to verify that your issue has not been addressed yet
  - type: textarea
    id: the-question
    attributes:
      label: Your question
    validations:
      required: true